### ISSUE TITLE
Error while installing using composer

### ISSUE THREAD

**Issue by Xbirdfr** [dereuromark/cakephp-tinyauth-backend#3]
Hello, after a fresh cakephp 4 install and a fresh tinyauth install, i wanted to setup the backend

so:  
`composer require dereuromark/cakephp-tinyauth-backend`

and i got : 

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for dereuromark/cakephp-tinyauth-backend ^0.1.1 -> satisfiable by dereuromark/cakephp-tinyauth-backend[0.1.1].
>     - dereuromark/cakephp-tinyauth-backend 0.1.1 requires cakephp/cakephp ^3.8.0 -> satisfiable by cakephp/cakephp[3.8.0, 3.8.0-RC1, 3.8.0-RC2, 3.8.0-RC3, 3.8.0-beta1, 3.8.1, 3.8.10, 3.8.11, 3.8.12, 3.8.13, 3.8.2, 3.8.3, 
> 3.8.4, 3.8.5, 3.8.6, 3.8.7, 3.8.8, 3.8.9, 3.9.0, 3.9.0-RC1, 3.9.0-RC2, 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.5, 3.x-dev] but these conflict with your requirements or minimum-stability.
> 
> 
> Installation failed, reverting ./composer.json to its original content.

this is my composer file: 

> {
>     "name": "cakephp/app",
>     "description": "CakePHP skeleton app",
>     "homepage": "https://cakephp.org",
>     "type": "project",
>     "license": "MIT",
>     "require": {
>         "php": ">=7.2",
>         "cakephp/cakephp": "~4.2.0",
>         "cakephp/migrations": "^3.0",
>         "cakephp/plugin-installer": "^1.3",
>         "dereuromark/cakephp-tinyauth": "^3.0",
>         "mobiledetect/mobiledetectlib": "^2.8"
>     },
>     "require-dev": {
>         "cakephp/bake": "^2.3",
>         "cakephp/cakephp-codesniffer": "~4.2.0",
>         "cakephp/debug_kit": "^4.4",
>         "josegonzalez/dotenv": "^3.2",
>         "phpunit/phpunit": "~8.5.0 || ^9.3",
>         "psy/psysh": "@stable"
>     },
>     "suggest": {
>         "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
>         "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan/Psalm compatibility.",
>         "phpstan/phpstan": "PHPStan focuses on finding errors in your code without actually running it. It catches whole classes of bugs even before you write tests for the code."
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "src/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "App\\Test\\": "tests/",
>             "Cake\\Test\\": "vendor/cakephp/cakephp/tests/"
>         }
>     },
>     "scripts": {
>         "post-install-cmd": "App\\Console\\Installer::postInstall",
>         "post-create-project-cmd": "App\\Console\\Installer::postInstall",
>         "check": [
>             "@test",
>             "@cs-check"
>         ],
>         "cs-check": "phpcs --colors -p  src/ tests/",
>         "cs-fix": "phpcbf --colors -p src/ tests/",
>         "stan": "phpstan analyse",
>         "test": "phpunit --colors=always"
>     },
>     "prefer-stable": true,
>     "config": {
>         "sort-packages": true
>     }
> }

**Comment by dereuromark** [comment]
The TinyAuthBackend version wasnt tagged so far, you had to use dev-master here.
I now tagged https://github.com/dereuromark/cakephp-tinyauth-backend/releases/tag/1.0.0-beta
Make sure to use ^1.0.0@beta for now then.
