### ISSUE TITLE
Acl normalizePath Issue

### ISSUE THREAD

**Issue by sanjeevdivekar** [dereuromark/cakephp-tinyauth-backend#4]
While saving admin/Dashboard::* aclPath is saves as Admin/Dashboard::* which doesn't work.

As controllers are in /src/Controller/Admin which are only accessible via http://localhost:8765/admin url

**Comment by dereuromark** [comment]
Please follow docs. Admin is correct.

**Comment by dereuromark** [comment]
Docs explain how the internal cake naming differs from inflected url result.

**Comment by sanjeevdivekar** [comment]
Well, I am missing something.

Following is my code without cakephp-tinyauth-backend which is running perfectly.

I am using CakePHP 3.8.13

**routes.php**
Router::prefix('admin', function (RouteBuilder $routes) {
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.
    $routes->connect('/', ['controller' => 'Account', 'action' => 'login']);
    $routes->fallbacks(DashedRoute::class);
});

**auth_acl.ini**
[admin/Dashboard]
* = root, admin, ba

**src/Controller/Admin/DashboardController.php**
namespace App\Controller\Admin;
use App\Controller\AppController;

class DashboardController extends AppController
{
    public function initialize() {
        parent::initialize();
    }
	
    public function index() {     
    }  
}

Thanks,

**Comment by dereuromark** [comment]
`Router::prefix('Admin'`
See also core docs on prefixing.

Also see linked demo projects and sandbox, as they show it as well.

**Comment by sanjeevdivekar** [comment]
I am using CakePHP 3.8.13

**Comment by dereuromark** [comment]
Ah, thats important info, then lowercase. 
See also the docs and Demo apps
